### PR TITLE
Make BaseRoute class as a grouped route

### PR DESCRIPTION
**Pull request by rendyananta**
Add a new class for support adding middleware, domain and regex matching route

remove method `$this->prefix()`. This removal also reduces boilerplate. Using -g flag when creating route class, afterward you can use the route class as usual but without `$this->prefix` method

This pull request won't make any running library fail to run. It will run well as usual. But if you want to use this feature you just need to extend your route class with GroupRoute class

### CODE REVIEW

**Comment by muhajirinlpu** [comment]
Please add some documentation

**Comment by rendyananta** [comment]
on my way

**Comment by veelasky** [comment]
@rendyyangasli Aq sering gawe this->prefix johnn

**Comment by rendyananta** [comment]
please review my changes at 
a6cfd57

**Pull request merged**
